# Generated by Django 2.1 on 2018-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikroy', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
