# Generated by Django 2.0.7 on 2018-08-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20180726_0310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog_Post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
