# Generated by Django 2.0.7 on 2018-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20180803_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
