# Generated by Django 2.0.7 on 2018-07-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catagory',
            field=models.CharField(default='Mobile', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
