# Generated by Django 2.0.7 on 2018-08-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.Catagory'),
        ),
    ]
