# Generated by Django 2.0.7 on 2018-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='photo',
            field=models.ImageField(default='NO IMage', upload_to=''),
            preserve_default=False,
        ),
    ]
