# Generated by Django 2.0.7 on 2018-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='photo',
            field=models.ImageField(upload_to='blog_image'),
        ),
    ]
