# Generated by Django 2.0.7 on 2018-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180721_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='photo',
            field=models.ImageField(upload_to='blog_iamge'),
        ),
    ]
