# Generated by Django 2.1 on 2018-09-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bslsnce',
            new_name='balance',
        ),
    ]
