# Generated by Django 2.0.7 on 2018-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll', models.IntegerField()),
                ('Result', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
            ],
        ),
    ]
