# Generated by Django 2.0.7 on 2018-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='Divition',
            field=models.CharField(default='dhaka', max_length=50),
            preserve_default=False,
        ),
    ]
